version: '3.8'
services:
  backup_client:
    build:
      context: Dockerfiles/backup_client
    image: tools/backup_client
    environment:
      SFTPPORT: ${SFTPPORT:-22}
      SFTPUSER: ${SFTPUSER:-backup_user}
      SFTPPASSWORD: ${SFTPPASSWORD:-backup_password}
      SFTPHOST: ${SFTPHOST:-backup.server.lan}
      SFTPREMOTE_DIR: ${SFTPREMOTE_DIR:-/backups}
      SFTPFILE_TO_UPLOAD: ${SFTPFILE_TO_UPLOAD:-/backupfolder/backupfile}
    volumes:
      - ./backup_server/user_ssh_keys/docker_backups.key:/root/.ssh/id_rsa:rw
      - ./backup_server/user_ssh_keys/docker_backups.key.pub:/root/.ssh/id_rsa.pub:rw