version: '3.8'
services:
  backup_client:
    build:
      context: Dockerfiles/backup_client
    image: tools/backup_client
    environment:
      SFTPPORT: ${SFTPPORT:-22}
      SFTPUSER: ${SFTPUSER:-docker_backups}
      SFTPPASSWORD: ${SFTPPASSWORD:-docker_backups}
      SFTPORIGINFOLDER:
      SFTPHOST: ${SFTPHOST}
      SFTPREMOTE_DIR: ${SFTPREMOTE_DIR}
      SFTPFILE_TO_UPLOAD: ${SFTPFILE_TO_UPLOAD:-/backupfolder/backupfile}
    volumes:
      - ./backup_server/user_ssh_keys/docker_backups.key:/root/.ssh/id_rsa:ro
      - ./backup_server/user_ssh_keys/docker_backups.key.pub:/root/.ssh/id_rsa.pub:ro