version: '3.8'
services:
  backup_dealer:
    build:
      context: Dockerfiles/backup_client
    image: tools/backup_client
    environment:
      SFTPPORT: ${SFTPPORT}
      SFTPUSER: ${SFTPUSER}
      SFTPHOST: ${SFTPHOST}
      SFTPDIR: ${SFTPDIR}
      PREFIX: ${PREFIX}
      VERBOSE: '' # Empty means false
    volumes:
      - "./backup_server/user_ssh_keys/docker_backups.key:/root/.ssh/id_rsa:ro"
      - "./backup_server/user_ssh_keys/docker_backups.key.pub:/root/.ssh/id_rsa.pub:ro"
      - "backup_volume:/master/:ro"

volumes:
  backup_volume:
    name: ${VOLUME_TO_BK}
    external: true