#docker-compose.yml
version: '3.8'
services:
  nginx:
   image: nginx
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - "nginx_logs:/var/log/nginx:rw"
    - "./config/nginx/web.conf:/etc/nginx/conf.d/web.conf:ro"
    - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    - "${LOCAL_PUBLIC_WEB_PATH}:/var/www:ro"
    - "./config/cert_ssl:/shared/ssl"
   deploy:
    restart_policy:
     condition: on-failure
   restart: on-failure
   depends_on:
     - php
   networks:
    - shop_net

  php:
   build:
    context: Dockerfiles
    dockerfile: php
   image: filtershop/php
   deploy:
    restart_policy:
     condition: on-failure
   configs:
    - uid="${UID:-1000}"
    - gid="${GID:-1000}"
   volumes:
    - "${LOCAL_PUBLIC_WEB_PATH}:/var/www:rw"
   environment:
    DB_LOCATION: "${DB_LOCATION:-postgresql}"
    HOSTNAME: "${HOSTNAME:-localhost}"
   links:
    - "${DB_LOCATION:-postgresql}"
   networks:
    - shop_net

  postgresql:
   build:
    context: Dockerfiles/postgresql
   image: filtershop/postgresql
   deploy:
    restart_policy:
     condition: on-failure
   restart: on-failure
   environment:
    POSTGRES_USER: "${DATABASE_USER}"
    POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    BUILD_DATABASE_LIST: "${BUILD_DATABASE_LIST}"
   volumes:
    - type: volume
      source: "postgresql_volume"
      target: "/var/lib/postgresql/data"
      volume:
       nocopy: true
   networks:
    - shop_net

  portainer:
   image: portainer/portainer-ce
   ports:
    - "9000:9000"
   volumes:
    - "portainer_data:/data"
    - "/var/run/docker.sock:/var/run/docker.sock"
   deploy:
    restart_policy:
     condition: on-failure
    mode: replicated
    placement:
     constraints: [node.role == manager]
   restart: on-failure
   networks:
    - agent_network

  adminer:
   image: adminer
   deploy:
    restart_policy:
     condition: on-failure
   restart: on-failure
   ports:
    - "8080:8080"
   links:
    - "${postgresql_LOCATION:-postgresql}"
   environment:
    ADMINER_DEFAULT_SERVER: "${DB_LOCATION:-postgresql}"
   networks:
    - shop_net

networks:
  shop_net:
   driver: bridge
  agent_network:
   driver: overlay
   attachable: true
volumes:
  postgresql_volume:
   external: false
  portainer_data:
  nginx_logs:
