version: '3'
services:
    nginx_shop:
       image: nginx
       ports:
         - "80:80"
         - "443:443"
       volumes:
         - ./config/nginx/web.conf:/etc/nginx/conf.d/web.conf:ro
         - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
         - ./config/filterweb/:/var/www
         - ./config/cert_ssl:/shared/ssl
       links:
         - php
       networks:
         db_net:
           ipv4_address: 10.24.1.4
    php:
      build:
        context: dockerfiles
        dockerfile: dockerfiles/php
      image: filtershop/php
      volumes:
#        - ./config/filterweb/:/code
#        - ./config/php/php.ini:/usr/local/etc/php/php.ini
        - ./config/filterweb/:/var/www
      links:
        - db
      networks:
       db_net:
         ipv4_address: 10.24.1.3

    db:
      build:
        context: dockerfiles/postgresql
      image: filtershop/postgresql
      ports:
        - target: 5432 # docker port
          published: 5432 # published port
          protocol: tcp
      environment:
        POSTGRES_PASSWORD: test
        POSTGRES_USER: test
        BUILD_DATABASE_LIST: ["shop" "contact_form"]
#        POSTGRES_DB: shop_db
        POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      volumes:
        - ./volumes/postgres/data:/var/lib/postgresql/data
      networks:
        db_net:
          ipv4_address: 10.24.1.2
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
networks:
  db_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.24.1.0/24
         gateway: 10.24.1.1
