version: '3'
services:
    php-apache:
        image: php:7.1.2-apache 
        ports:
           - target: 80 # docker port
             published: 80 # published port
             protocol: tcp
        volumes:
          - ./volumes/web/:/var/www/
          - ./volumes/sites-available/webstorm.conf:/etc/apache2/sites-available/000-default.conf:ro
#          - ./volumes/www/html:/var/www/html:ro
#          - ./volumes/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
#          - type: bind
#            source: ./volumes/www/html
#            target: /var/www/html
#            read_only: true
#        links:
#            - 'mariadb'
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: example
#       volumes:
#         - ./volumes/postgres/data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
