version: '3.8'
services:
           nginx_pub:
            image: nginx
            ports:
             - "80:80"
             - "443:443"
            volumes:
             - "./config/nginx/web.conf:/etc/nginx/conf.d/web.conf:ro"
             - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
             - "${LOCAL_PUBLIC_WEB_PATH}:/var/www:ro"
             - "./config/cert_ssl:/shared/ssl"
            links:
             - php
            depends_on:
             - php
            networks:
             - shop_net

           php:
            build:
             context: Dockerfiles
             dockerfile: php
            configs:
             - uid="${UID:-1000}"
             - gid="${GID:-1000}"
            image: filtershop/php
            volumes:
           #        - ./config/php/php.ini:/usr/local/etc/php/php.ini
             - "${LOCAL_PUBLIC_WEB_PATH}:/var/www:rw"
            environment:
             SHOP_DB_LOCATION: "${SHOP_DB_LOCATION:-shop_db}"
             HOSTNAME: "${HOSTNAME:-localhost}"
            links:
             - "${SHOP_DB_LOCATION:-shop_db}"
            networks:
             - shop_net

           shop_db:
            build:
             context: Dockerfiles/postgresql
#             args:
            image: filtershop/postgresql
#            ports:
#             - target: 5432 # docker port
#               published: 5432 # published port
#               protocol: tcp
            environment:
             POSTGRES_USER: "${SHOP_DATABASE_USER}"
             POSTGRES_PASSWORD: "${SHOP_DATABASE_PASSWORD}"
             POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
             BUILD_DATABASE_LIST: "${BUILD_DATABASE_LIST}"
            volumes:
             - type: volume
               source: shop_db_volume
               target: /var/lib/postgresql/data
               volume:
                nocopy: false
            networks:
             - shop_net

           adminer:
            image: adminer
            restart: always
            ports:
             - 8080:8080
            links:
             - "${SHOP_DB_LOCATION:-shop_db}"
            environment:
             ADMINER_DEFAULT_SERVER: "${SHOP_DB_LOCATION:-shop_db}"
            networks:
             - shop_net
networks:
  shop_net:
   driver: bridge
   ipam:
    driver: default
    config:
     - subnet: 10.24.1.0/24
       gateway: 10.24.1.1
volumes:
  shop_db_volume:
   external: false