version: '3.8'
services:
 bakup_server: # PORT 23
  image: atmoz/sftp
  ports:
    - target: 22
      published: 23
      protocol: tcp
      mode: host
  volumes:
    # SSH connection keys
    - ./ssh_keys/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
    - ./ssh_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
    - ./ssh_keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
    - ./ssh_keys/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro

    # USERS
    # User_list
    - ./users.conf:/etc/sftp/users.conf:ro
    # SSH authentication keys
    - ./user_ssh_keys/docker_backups.key.pub:/home/docker_backups/.ssh/authorized_keys:ro
#     Backup postgres volume
#    - postgres_shop_backups_volume:/home/docker_backups/backups/postgres:rw
    - type: volume
      source: backups_volume
      target: /home/docker_backups/backups/

      volume:
        nocopy: true
volumes:
  backups_volume:
    external: false